# Generated by Django 4.2.7 on 2023-11-08 03:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('nickname', models.CharField(default='', max_length=124)),
                ('username', models.CharField(blank=True, max_length=128, unique=True)),
                ('phone', models.CharField(max_length=128)),
                ('birth', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=128)),
                ('is_certified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
