# Generated by Django 4.2.7 on 2023-11-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_plan_day_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='memo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
